/**
 * 
 */

package org.opentides.dao;

import org.opentides.bean.SystemCodes;
import org.opentides.persistence.BaseEntityDAO;



/**
 * This is the dao interface for SystemCodes.
 * Auto generated by high tides.
 * @author hightides
 */
 
public interface SystemCodesDao extends BaseEntityDAO<SystemCodes, Long> {

}