/*
 * UserDefinedRecordServiceImpl.java
 */
package org.opentides.service.impl;

import org.opentides.bean.UserDefinedRecord;
import org.opentides.service.UserDefinedRecordService;

/**
 * This is the service implementation for UserDefinedRecord.
 * Auto generated by high tides.
 * @author hightides
 *
 */
public class UserDefinedRecordServiceImpl extends BaseCrudServiceImpl<UserDefinedRecord>
		implements UserDefinedRecordService {

//-- Start custom codes. Do not delete this comment line.
//-- End custom codes. Do not delete this comment line.
}
