/*
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.    
 */

/*
 * UserDefinedFieldService.java
 */
package org.opentides.service;

import java.util.List;
import java.util.Map;

import org.opentides.bean.UserDefinedField;

/**
 * This is the service interface for UserDefinedField.
 * Auto generated by high tides.
 * @author hightides
 */
 
public interface UserDefinedFieldService extends BaseCrudService<UserDefinedField> {
//-- Start custom codes. Do not delete this comment line.
	/**
	 * Retrieves the list of meta field definition for the given class.
	 * 
	 * @param Class clazz - the class containing the meta fields
	 * @return List<UserDefinedField>
	 */
	public List<UserDefinedField> findMetaByClass(String clazz);
	
	/**
	 * Retrieves a map of dropdown values enabled for
	 * the user defined field of the given class.
	 * Map returned by this method can be used as reference data.
	 * 
	 * @return Map<String, Object>
	 */
	public Map<String, Object> getDropDownReferenceData(String clazz);
	
//-- End custom codes. Do not delete this comment line.
}
