/**
 * 
 */
package org.opentides.dao.impl;


import org.opentides.bean.SystemCodes;
import org.opentides.dao.SystemCodesDao;
import org.opentides.persistence.impl.BaseEntityDAOJpaImpl;


/**
 * This is the dao implementation for SystemCodes.
 * Auto generated by high tides.
 * @author hightides
 *
 */
public class SystemCodesJpaDaoImpl extends BaseEntityDAOJpaImpl<SystemCodes, Long>
		implements SystemCodesDao {

}
