/* 
 * UserDefinedRecordDAO.java
 */
package org.opentides.persistence;

import org.opentides.bean.UserDefinedRecord;

/**
 * This is the dao interface for UserDefinedRecord.
 * Auto generated by high tides.
 * @author hightides
 */
 
public interface UserDefinedRecordDAO extends BaseEntityDAO<UserDefinedRecord, Long> {
//-- Start custom codes. Do not delete this comment line.
//-- End custom codes. Do not delete this comment line.
}