/*
 * UserDefinedRecordService.java
 */
package org.opentides.service;

import org.opentides.bean.UserDefinedRecord;

/**
 * This is the service interface for UserDefinedRecord.
 * Auto generated by high tides.
 * @author hightides
 */
 
public interface UserDefinedRecordService extends BaseCrudService<UserDefinedRecord> {
//-- Start custom codes. Do not delete this comment line.
//-- End custom codes. Do not delete this comment line.
}
