/*
   Licensed to the Apache Software Foundation (ASF) under one
   or more contributor license agreements.  See the NOTICE file
   distributed with this work for additional information
   regarding copyright ownership.  The ASF licenses this file
   to you under the Apache License, Version 2.0 (the
   "License"); you may not use this file except in compliance
   with the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing,
   software distributed under the License is distributed on an
   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   KIND, either express or implied.  See the License for the
   specific language governing permissions and limitations
   under the License.    
 */

package org.opentides.persistence;

import java.util.List;

import org.opentides.bean.DynamicReport;

/**
 * This is the dao interface for Report.
 * Auto generated by high tides.
 * @author hightides
 */
 
public interface ReportDAO extends BaseEntityDAO<DynamicReport, Long> {
//-- Start custom codes. Do not delete this comment line.
	
	/**
	 * used for retrieving list of ParameterOption objects by queryString
	 * @param queryString
	 */
	public List<Object[]> getParamOptionResults(String queryString);

	public List<DynamicReport> findAllReportsOrderByReportGroup();
//-- End custom codes. Do not delete this comment line.
}