/*
 * UserDefinedRecordDAOJpaImpl.java
 */
package org.opentides.persistence.impl;

import org.opentides.bean.UserDefinedRecord;
import org.opentides.persistence.UserDefinedRecordDAO;


/**
 * This is the dao implementation for UserDefinedRecord.
 * Auto generated by high tides.
 * @author hightides
 *
 */
public class UserDefinedRecordDAOJpaImpl extends BaseEntityDAOJpaImpl<UserDefinedRecord, Long>
		implements UserDefinedRecordDAO { 
	
//-- Start custom codes. Do not delete this comment line.
//-- End custom codes. Do not delete this comment line.
}
